### ISSUE TITLE
1.16.5-2 Fabric version structures not spawing

### ISSUE THREAD

**Issue by GregoryTheGamer** [alexsocha/luckyblock#30]
Hello I noticed that someone else mentioned that the wishing wells were not spawning [https://github.com/alexsocha/luckyblock/issues/24](url)
however through my testing of a clean install... all structures will not spawn in the latest Fabric version of the mod, I tried messing with the configs, changing gamemodes, but nothing works, all structures that usually spawn through lucky blocks won't spawn under any circumstances. Could you please address this issue for Fabric users please? Thanks, Greg

**Comment by Rdna123** [comment]
In the logs it says could not load [stucture].txt I will try to rerun this
when I can download everything to get full log.

**Comment by alexsocha** [comment]
I'm still having trouble replicating this, but it would be really helpful if you could:
1. Let me know what OS you are using (windows, macos, etc)
2. In the Minecraft launcher, open settings and tick `Open output log when Minecraft: Java Edition starts`, then start the game and post the log here
3. Tell me which files/folders you can see in `.minecraft/config/lucky/1.16.5-2-fabric/`

**Comment by GregoryTheGamer** [comment]
> I'm still having trouble replicating this, but it would be really helpful if you could:
> 
> * Let me know what OS you are using (windows, macos, etc)
> * In the Minecraft launcher, open settings and tick `Open output log when Minecraft: Java Edition starts`, then start the game and post the log here
> * Tell me which files/folders you can see in `.minecraft/config/lucky/1.16.5-2-fabric/`

How are you having trouble replicating this? Its literally every time you break a lucky block and no structure spawns? I mean I'll do those steps you asked but I don't understand how you don't realize the current version of the fabric mod the structures are not spawning through breaking lucky blocks?

**Comment by GregoryTheGamer** [comment]
The OS I am using is Windows
and these are my files
![screen1](https://user-images.githubusercontent.com/24637139/118304290-197e1500-b4ac-11eb-8890-e04c8b5df874.png)
![screen2](https://user-images.githubusercontent.com/24637139/118304298-1c790580-b4ac-11eb-8cbf-f1569e39a584.png)
![screen3](https://user-images.githubusercontent.com/24637139/118304304-1daa3280-b4ac-11eb-8830-b85e9183c9aa.png)
![screen4](https://user-images.githubusercontent.com/24637139/118304308-1edb5f80-b4ac-11eb-90ee-9c35ed6322aa.png)

**Comment by GregoryTheGamer** [comment]
and here is the log
[latest.log](https://github.com/alexsocha/luckyblock/files/6480212/latest.log)

**Comment by alexsocha** [comment]
Thanks so much! The issue was to do with paths of windows using `\` instead of `/`, it should be fixed in the latest release (I haven't tested it yet though)

**Comment by GregoryTheGamer** [comment]
Uh seems like it didn't work, its still not spawning structures?

**Comment by alexsocha** [comment]
My bad, made a small mistake in the last release, and this time I've actually tested it on a windows VM

**Comment by GregoryTheGamer** [comment]
Alright it works now, thanks for fixing the issue. Might as well close this now.
